"confirm tx on main net" restyled
ethereum/remix-project pull request #1167
Opened 2021-05-06 17:43 UTC by LianaHus

fix https://github.com/ethereum/remix-project/issues/1048

2021-05-13 03:46 UTC, ryestew reviewed
Right now in this PR the modal looks like this:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/6050001/118074379-c6a54000-b37b-11eb-81ea-06d2e1217733.png">

Here's a shorter line:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/6050001/118074630-534ffe00-b37c-11eb-9366-77610d93042e.png">

2021-05-13 03:54 UTC, ryestew requested changes

2021-05-13 03:54 UTC, ryestew commented on apps/remix-ide/src/app/ui/confirmDialog.js
> +      <div>You are about to create a transaction on the main network. Confirm details to send to your provider.</div>
<div>You are about to create a transaction on the main network. <br>Confirm the details to send to your provider.</div>

2021-05-13 03:54 UTC, ryestew commented on apps/remix-ide/src/app/ui/confirmDialog.js
> +          <span>Gwei (visit <a target='_blank' href='https://ethgasstation.info'>ethgasstation.info</a> to get more info about gas price)</span>
<span>Gwei (visit <a target='_blank' href='https://ethgasstation.info'>ethgasstation.info</a> for current gas price info)</span>

2021-05-17 07:48 UTC, LianaHus commented
@ryestew done!
thanks

2021-05-20 07:24 UTC, LianaHus commented
@ryestew could you please review again? TIA

2021-05-20 10:02 UTC, yann300 commented
changes sounds good, waiting for @ryestew approval

2021-05-21 03:09 UTC, ryestew commented on apps/remix-ide/src/app/ui/confirmDialog.js
> +      <div>You are about to create a transaction on the main network. Confirm the details to send to your provider.</div>
For many users, I think the word **provider** is not clear.  Is this line better: 

You are about to create a transaction on the main network. Confirm the details to send to your provider.  The provider for many users is MetaMask.  Confirming the details only sends the info to the provider -where in turn, you will need to sign the transaction to send it to the main network.

or 

You are about to create a transaction on the main network. Confirm the details to send the info to your provider.  The provider for many users is MetaMask.  The provider will ask you to sign the transaction before it is sent to the main network.

2021-05-25 20:02 UTC, ryestew approved these changes

2021-05-26 15:22 UTC, merged