Fixing CSS formatting issues
ethereum/remix-project pull request #1409
Opened 2021-07-27 10:16 UTC by rorye

Fixes #1378 

Before: 

<img width="480" alt="Screen Shot 2021-07-27 at 8 15 20 pm" src="https://user-images.githubusercontent.com/157779/127137629-ad6d0c83-808b-4d96-ba6a-0acce34d5ac7.png">

After:

<img width="486" alt="Screen Shot 2021-07-27 at 8 14 30 pm" src="https://user-images.githubusercontent.com/157779/127137654-7d887e3b-73b1-4291-af08-e19668678e15.png">

2021-07-27 10:58 UTC, LianaHus commented
Thanks for the PR

IMHO we should change the font color of the theme as well

it's the main color of text, you can find it here:

.ace-remixDark {\
  background-color: #222336;\
  color: #a2a3bd;\
  }\

#a2a3bd => #d5d5e9

2021-07-27 11:17 UTC, LianaHus requested changes
see the comment

2021-07-28 06:54 UTC, rorye commented
> Thanks for the PR
> 
> IMHO we should change the font color of the theme as well
> 
> it's the main color of text, you can find it here:
> 
> .ace-remixDark {
> background-color: #222336;
> color: #a2a3bd;
> }\
> 
> #a2a3bd => #d5d5e9

Have made this change now, thanks.

2021-07-28 13:18 UTC, LianaHus approved these changes

2021-07-29 09:27 UTC, closed without merging