Panels
ethereum/remix-project pull request #1857
Opened 2021-12-23 15:29 UTC by bunsenstraat

2022-01-04 11:27 UTC, yann300 commented on apps/remix-ide/src/app.js
>      Registry.getInstance().put({ api: self.mainview, name: 'mainview' })
This can be removed too I think

2022-01-04 11:29 UTC, yann300 commented on apps/remix-ide/src/app.js
>      await self.appManager.activatePlugin(['mainPanel', 'menuicons', 'tabs'])
it's already being activated above

2022-01-04 11:33 UTC, yann300 commented on apps/remix-ide/src/app/components/side-panel.tsx
> +    ReactDOM.render(<RemixPluginPanel header={<RemixUIPanelHeader plugins={this.plugins}></RemixUIPanelHeader>} plugins={this.plugins}/>, this.sideelement)
I don't think `</RemixUIPanelHeader>` is needed here

2022-01-04 11:34 UTC, yann300 commented on apps/remix-ide/src/app/components/side-panel.tsx
> +    ReactDOM.render(<RemixPluginPanel header={<RemixUIPanelHeader plugins={this.plugins}></RemixUIPanelHeader>} plugins={this.plugins}/>, this.sideelement)
or wait yes my bad, this is fine

2022-01-04 11:55 UTC, yann300 commented on libs/remix-ui/terminal/src/lib/remix-ui-terminal.tsx
> +        setTimeout(() => {
did you want to add `scriptRunnerDispatch` inside it?

2022-01-04 12:03 UTC, yann300 commented
it seems the url parameter `embed` and `minimizesidepanel` sill need to be added.

2022-01-04 12:17 UTC, bunsenstraat commented
@yann300 what does embed parameter do?

2022-01-04 12:18 UTC, bunsenstraat commented
@yann300 minimizesidepanel is not covered by any test, neither is minimizeterminal

2022-01-04 13:04 UTC, yann300 commented
embed, just minimize terminal and side panel.

2022-01-05 09:14 UTC, LianaHus commented on libs/remix-ui/panel/src/lib/plugins/panel.css
> +.panel {
most of those properties you can set as a bootstrap class, which is preferable

2022-01-06 12:24 UTC, ioedeveloper requested changes

2022-01-06 12:24 UTC, ioedeveloper commented on libs/remix-ui/panel/.eslintrc.json
> +{
Update linting rules to default.

```
{
  "extends": ["plugin:@nrwl/nx/react", "../../../.eslintrc"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {}
    },
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "rules": {}
    }
  ]
}
```

2022-01-06 12:51 UTC, LianaHus approved these changes

2022-01-06 13:06 UTC, ioedeveloper approved these changes

2022-01-06 13:06 UTC, merged