Add provider
ethereum/remix-project pull request #2219
Opened 2022-03-21 16:49 UTC by yann300

This PR automatically add hardhat, ganache and wallet connect provider when Remix loads.
see https://github.com/bunsenstraat/remix-walletconnect/pull/1 for wallect connect compatibility

2022-03-22 06:00 UTC, Aniket-Engg requested changes

2022-03-22 06:00 UTC, Aniket-Engg commented on apps/remix-ide/src/app/tabs/abstract-provider.tsx
> +  name: 'hardhat-provider',
This name should be updated

2022-03-23 10:49 UTC, ioedeveloper commented on libs/remix-ui/run-tab/src/lib/actions/index.ts
> +  console.log('adding ext provider', network)
Do we need this log?

2022-03-30 05:50 UTC, ioedeveloper submitted a review, later dismissed
Ganache and Hardhat provider modal only pops up once. If the cancel button is clicked to close the modal, the modal no longer pops up.

2022-03-30 10:19 UTC, yann300 commented
> Ganache and Hardhat provider modal only pops up once. If the cancel button is clicked to close the modal, the modal no longer pops up.

done

2022-04-06 06:25 UTC, Aniket-Engg commented on package.json
> +    "nightwatch_local_search": "npm run build:e2e && nightwatch --config dist/apps/remix-ide-e2e/nightwatch.js dist/apps/remix-ide-e2e/src/tests/providers.test.js --env=chromeDesktop",
script name should be fixed

2022-04-06 07:03 UTC, yann300 commented on package.json
> +    "nightwatch_local_search": "npm run build:e2e && nightwatch --config dist/apps/remix-ide-e2e/nightwatch.js dist/apps/remix-ide-e2e/src/tests/providers.test.js --env=chromeDesktop",
done

2022-04-06 09:00 UTC, Aniket-Engg approved these changes

2022-04-06 10:28 UTC, merged