fix calling hardhat compile in win32
ethereum/remix-project pull request #3524
Opened 2023-03-14 14:34 UTC by yann300

fix https://github.com/ethereum/remix-desktop/issues/183

2023-03-14 15:02 UTC, joeizang approved these changes

2023-03-14 15:04 UTC, bunsenstraat commented on libs/remixd/src/services/hardhatClient.ts
> +      const cmd = utils.normalizePath(`./node_modules/.bin/hardhat compile --config ${utils.normalizePath(configPath)}`)
this will only work if node is in the path that electron has when running standalone. 
[Hardhat Compilation]: env: node: No such file or directory

2023-03-14 15:19 UTC, bunsenstraat requested changes
this will only work if node is in the path that electron has when running standalone.
which it isn't by default, could be in brew, /usr/local/bin, anything, without the path of the user we won't know. On my system it says when I run this in a standalone remix desktop build
[Hardhat Compilation]: env: node: No such file or directory

2023-03-15 08:15 UTC, bunsenstraat approved these changes

2023-03-15 09:38 UTC, merged