improvements in pride theme
ethereum/remix-project pull request #3807
Opened 2023-06-16 09:23 UTC by LianaHus

2023-06-19 10:27 UTC, Aniket-Engg reviewed
![Screenshot 2023-06-19 at 3 57 08 PM](https://github.com/ethereum/remix-project/assets/30843294/aff56b19-dae8-4478-b55a-581e00fd8b97)

To me SUT buttons look like this, which seems bad.

2023-06-21 10:30 UTC, joeizang requested changes
![image](https://github.com/ethereum/remix-project/assets/4255962/5eeb1cfb-f135-4228-8e5e-0dfca74988bb)

I think the choice of black text and icons for primary buttons is an issue because pride is a light theme. Primary colors should contrast with light text and icons. See the image below from cerulean.

![image](https://github.com/ethereum/remix-project/assets/4255962/b512427b-1994-4449-a697-fdc8b5165161)

2023-06-21 10:30 UTC, joeizang commented
Oh and the thick border around the vertical icons panel cuts into the space that badges should take. See image above

2023-06-27 08:39 UTC, joeizang approved these changes

2023-06-27 08:44 UTC, merged