disable verify for not supported VM
ethereum/remix-project pull request #3840
Opened 2023-06-21 11:43 UTC by Aniket-Engg

Related to #3813

2023-06-21 13:15 UTC, LianaHus commented
I thought we should have a tooltip on verify btn when it is disabled, it is a good practice to give a hint on disabled btn.
Is it possible to add this?

2023-06-21 13:15 UTC, LianaHus requested changes
missing a tooltip on verify btn when it is disabled

2023-06-21 15:06 UTC, Aniket-Engg commented
See, tooltip is there: https://github.com/ethereum/remix-project/blob/master/apps/etherscan/src/app/components/SubmitButton.tsx#L19 but it is not easily visible. May be needs some improvement

2023-06-22 08:54 UTC, LianaHus approved these changes

2023-06-22 09:02 UTC, merged