Static Analyzers Run Button Fix
ethereum/remix-project pull request #3876
Opened 2023-06-30 10:55 UTC by joeizang

fixes #3839

2023-06-30 16:22 UTC, Aniket-Engg reviewed
I think issue is also about to change the tooltip message as per discussion

2023-07-05 09:44 UTC, joeizang commented
> I think issue is also about to change the tooltip message as per discussion

This is a different pr @Aniket-Engg. The pr with improvements will be ready soon

2023-07-05 10:31 UTC, LianaHus requested changes

2023-07-05 10:31 UTC, LianaHus commented on apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts
> +function runTests(browser: NightwatchBrowser) {
you need a space here

2023-07-05 10:31 UTC, LianaHus commented on apps/remix-ide-e2e/src/tests/staticAnalysis.test.ts
> +function listSelectorContains(textsToFind: string[], selector: string, browser: NightwatchBrowser) {
you need a space here

2023-07-05 10:31 UTC, LianaHus commented on libs/remix-ui/static-analyser/src/lib/Button/StaticAnalyserButton.tsx
> +          </button>
indent

2023-07-05 10:31 UTC, LianaHus commented
how it was fixed exactly?

2023-07-05 11:14 UTC, Aniket-Engg commented
> > I think issue is also about to change the tooltip message as per discussion
> 
> This is a different pr @Aniket-Engg. The pr with improvements will be ready soon

In that case, can you update PR desc explaining the purpose of this PR?  Just to add, merging this  PR will close that issue, so I believe everything in that issue should fixed by this PR

2023-07-06 15:02 UTC, Aniket-Engg approved these changes
LGTM

2023-07-07 09:46 UTC, LianaHus approved these changes

2023-07-07 09:54 UTC, merged