left highlight for active plugin icon
ethereum/remix-project pull request #4292
Opened 2023-11-30 22:25 UTC by LianaHus

2023-12-01 05:29 UTC, vermouth22 approved these changes

2023-12-01 05:33 UTC, vermouth22 commented
Looks like some Chrome timeout issue? .... but otherwise looks cool.

2023-12-04 08:51 UTC, Aniket-Engg requested changes
This looks fine but I see you have reduced vertical gap between icons. And At some place icon highlight touches another icon

2023-12-05 14:47 UTC, Aniket-Engg approved these changes
LGTM!

2023-12-05 17:29 UTC, merged