Fix handling modal blur
ethereum/remix-project pull request #4456
Opened 2024-01-16 10:41 UTC by yann300

fix https://github.com/ethereum/remix-project/issues/4398

2024-01-27 02:08 UTC, ioedeveloper requested changes
I still get the error/bug behavior on the deploy preview link.

2024-01-29 08:37 UTC, Aniket-Engg commented
> I still get the error/bug behavior on the deploy preview link.

I can also reproduce the issue with deploy preview

2024-01-29 11:23 UTC, ioedeveloper approved these changes

2024-01-29 11:43 UTC, DOBEN commented
Works great now.

2024-01-30 10:42 UTC, merged