added alert for external plugins
ethereum/remix-project pull request #4502
Opened 2024-01-31 11:23 UTC by LianaHus

2024-01-31 14:53 UTC, ryestew requested changes

2024-01-31 14:53 UTC, ryestew commented on apps/remix-ide/src/app/tabs/locales/en/panel.json
> +  "panel.maintainedExternally": "Be aware that the plugin is not maintained by Remix",
"This plugin is not maintained by Remix"

2024-01-31 14:53 UTC, ryestew commented on apps/remix-ide/src/app/tabs/locales/en/pluginManager.json
> +  "pluginManager.maintainedExternally": "Be aware that the plugin is not maintained by Remix",
Should either be (I prefer the 1st option) :
"Not maintained by Remix"
or
"Be aware that this plugin is not maintained by Remix"

2024-02-01 09:23 UTC, Aniket-Engg reviewed
<img width="168" alt="Screenshot 2024-02-01 at 2 53 09 PM" src="https://github.com/ethereum/remix-project/assets/30843294/d9980b55-44b8-4a8b-add5-74b8163606aa">

This is on home tab, may be for cookbook

2024-02-01 09:55 UTC, Aniket-Engg approved these changes

2024-02-05 07:13 UTC, merged