Vyper Plugin Patch/Ui Updates
ethereum/remix-project pull request #4538
Opened 2024-02-15 09:05 UTC by joeizang

fixes #4537

2024-02-21 17:09 UTC, ryestew requested changes

2024-02-23 22:18 UTC, joeizang commented on apps/vyper/src/app/app.tsx
> +              </CustomAccordionToggle>
done

2024-02-26 04:32 UTC, ryestew reviewed
It would make a little more graphic sense if when you click the local compiler, the text box appears just below the radio buttons and not below the the advice text about where to put the pragma stuff.

I"ll have the link for the compiler version today. 

Will the snekmate repo be in this release - or the next one?

Is Ctrl +S working now?  I think it isn't

and the evm version isnt being returned yet from Ape - right?  Nor is the optimize - right?

2024-02-26 07:26 UTC, joeizang commented
> It would make a little more graphic sense if when you click the local compiler, the text box appears just below the radio buttons and not below the the advice text about where to put the pragma stuff.
> 
> I"ll have the link for the compiler version today.
> 
> Will the snekmate repo be in this release - or the next one?
> 
> Is Ctrl +S working now? I think it isn't
> 
> and the evm version isnt being returned yet from Ape - right? Nor is the optimize - right?

evm version isn't being returned by Apeworx yet.

Ctrl + S isn't working yet. That will come in the next release.

I will fix the placement of the warning message. 

Thanks @ryestew

2024-02-26 19:14 UTC, ryestew requested changes
- [x] For specifying the Vyper version, add this link
https://remix-ide.readthedocs.io/en/latest/vyper.html#specify-vyper-version

- [ ] The tab for compilation details doesn't say the contract's name - the title of the tab is contractName.  This needs to be updated.
- [x] When you switch to another vyper file, the compilation details button should go away - just like it does in Solidity file.
- [ ] I am not getting ctrl +s to work
- [ ] When I click on a compiler error, the cursor should jump to the that line in the editor.  That doesn't seem to be working now.

2024-02-27 05:40 UTC, ryestew approved these changes

2024-02-27 06:30 UTC, merged