feat: Adds default bug & feature request issue templates
ethereum/remix-project pull request #4715
Opened 2024-04-13 22:07 UTC by darigovresearch

Would resolve https://github.com/ethereum/remix-project/issues/4691 if merged

2024-04-14 10:53 UTC, TELLYWHALE approved these changes
Fixed the edges

2024-05-08 09:47 UTC, Aniket-Engg requested changes

2024-05-08 09:47 UTC, Aniket-Engg commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Browser [e.g. chrome, safari]
replace safari with firefox here

2024-05-08 09:47 UTC, Aniket-Engg commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - OS: [e.g. iOS]
update `iOS` with `Windows, Linux or MacOS`

2024-05-08 09:47 UTC, Aniket-Engg commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Smartphone (please complete the following information):**
Remix is not supported for smart phones, can you please remove this section?

2024-06-15 21:03 UTC, darigovresearch commented
Thanks for the feedback @Aniket-Engg ! 

Have made adjustments, do you need anything else to merge the pull request?

2024-06-17 04:44 UTC, Aniket-Engg approved these changes

2024-06-17 04:44 UTC, merged