Check for Zero Address
ethereum/remix-project pull request #4889
Opened 2024-06-16 09:57 UTC by devmev10

Added a require statement in the changeOwner function to ensure that the new owner is not set to the zero address. This prevents accidental loss of control over the contract.

2024-06-17 07:24 UTC, devmev10 commented
Thanks for the approval!

2024-06-17 12:16 UTC, Aniket-Engg requested changes
update e2e

2024-06-17 14:21 UTC, devmev10 commented
> update e2e

Is this request directed to me? 
If yes, can you clarify more please

2024-08-21 07:58 UTC, Aniket-Engg commented
continued in https://github.com/ethereum/remix-project/pull/5097

2024-08-21 07:58 UTC, closed without merging