Use remix plugin 0.3
ethereum/remix-project pull request #511
Opened 2020-10-19 15:24 UTC by yann300

2020-10-19 15:39 UTC, GrandSchtroumpf reviewed
In PluginManager rename : 
- `canActivate` to `canActivatePlugin`
- `canDeactivate` to `canDeactivatePlugin`

2020-10-19 15:39 UTC, GrandSchtroumpf commented on apps/remix-ide/package.json
> +    "@remixproject/engine-web": "^0.2.5",
Should be 0.3.0

2020-11-16 16:27 UTC, GrandSchtroumpf approved these changes

2020-11-16 16:27 UTC, GrandSchtroumpf commented on apps/remix-ide/src/app/components/plugin-manager-component.js
> +import { ViewPlugin } from '@remixproject/engine'
In 0.3.3 this should come from engine-web too

2020-11-16 16:27 UTC, GrandSchtroumpf commented on apps/remix-ide/src/app/tabs/debugger-tab.js
> +    // this.call('manager', 'activatePlugin', 'source-verification').catch(e => console.error(e))
You can remove

2020-11-16 16:27 UTC, GrandSchtroumpf commented on apps/remix-ide/src/remixAppManager.js
> +    return true // canActivate(from.name)
any plugin can activate another ?

2020-11-16 16:27 UTC, GrandSchtroumpf commented on apps/remix-ide/src/remixAppManager.js
> +    console.log('canDeactivatePlugin', from, to)
Maybe remove console.log

2020-11-16 16:27 UTC, GrandSchtroumpf commented on apps/remix-ide/src/remixAppManager.js
> +    console.log('manager has been registered')
same here

2020-11-16 16:27 UTC, GrandSchtroumpf commented on apps/remix-ide/src/remixAppManager.js
> +        plugin.url = 'ipfs://QmRWBCgCzKa1ixoVN9mvJACVuqWLRTRYS4sUJ9wzUBRHSf'
Why not setting it directly in the profile above ?

2020-11-16 16:27 UTC, GrandSchtroumpf commented on libs/remixd/package.json
> +    "@remixproject/plugin": "^0.3.2",
use version 0.3.3

2020-11-23 09:15 UTC, merged

2020-11-23 11:33 UTC, cleytontiagosorinho requested changes

2020-11-23 11:33 UTC, cleytontiagosorinho commented on workspace.json
> +              "tsc -p apps/remix-ide-e2e/tsconfig.e2e.json"
Sim

2020-11-23 11:33 UTC, cleytontiagosorinho commented on libs/remixd/package.json
> +    "@remixproject/plugin": "^0.3.3",
7139bd9c1eb73cd1b6ebff99f500b431a987f706

2020-11-23 11:33 UTC, cleytontiagosorinho approved these changes
7139bd9c1eb73cd1b6ebff99f500b431a987f706