[REFACTOR] Circuit compiler actions
ethereum/remix-project pull request #5238
Opened 2024-09-30 15:43 UTC by azarpoor

- improve coding structure of circuit compiler actions
- make it more readable 
- remove some additional codes 
- improve error handling

2024-09-30 17:55 UTC, azarpoor commented
@joeizang

2024-09-30 19:24 UTC, dIvaD8 commented on apps/circuit-compiler/src/app/actions/index.ts
> -      console.log('Existing circuit compilation in progress')
9   -     !==

2024-10-01 12:52 UTC, azarpoor commented on apps/circuit-compiler/src/app/actions/index.ts
> -      console.log('Existing circuit compilation in progress')
hey thank you i correct this check

2024-10-03 16:20 UTC, azarpoor commented
@bunsenstraat

2024-12-09 15:32 UTC, AmirH-A commented
hello hope your doing well , 

[Aniket-Engg](https://github.com/Aniket-Engg)

i have primary account which is this account with name AmirH-A 

i change the auther to this account , and if its needed to change commiter to this also i don't know  

i wanna mention this to you , thank you by the way

2024-12-17 10:58 UTC, ioedeveloper commented
@AmirH-A Can you rebase and fix the merge conflict?

2024-12-17 13:22 UTC, AmirH-A commented
> @AmirH-A Can you rebase and fix the merge conflict?

hey , yes of course

2024-12-17 14:02 UTC, AmirH-A commented
@ioedeveloper

2024-12-19 12:51 UTC, ioedeveloper commented on apps/circuit-compiler/src/app/actions/index.ts
> +  const data = await plugin.call('fileManager', 'readFile', path)
Missing parameter to fileManager plugin call `'opt?'` parameter. `"{ encoding: null }"`. The type definition for `fileManager` is not updated for this additional option. You can use // @ts-ignore to ignore the error.

2024-12-19 12:54 UTC, ioedeveloper requested changes

2024-12-19 12:54 UTC, ioedeveloper commented on apps/circuit-compiler/src/app/actions/index.ts
> +  return new Uint8Array(data.split(',').map(byte => parseInt(byte, 10)))
Also, `"data.split(',').map(byte => parseInt(byte, 10)"` is not needed if you are reading bytes from the `fileManager`

2024-12-19 13:58 UTC, AmirH-A commented
@ioedeveloper 

thank you for review

2025-01-06 09:58 UTC, ioedeveloper approved these changes

2025-01-06 13:37 UTC, Aniket-Engg commented
@azarpoor can you fix linting?

2025-01-06 14:07 UTC, AmirH-A commented
> @azarpoor can you fix linting?

hey , of course :+1:

2025-01-07 10:04 UTC, Aniket-Engg commented
circom related e2e are failing @azarpoor @ioedeveloper

2025-01-07 10:06 UTC, AmirH-A commented
> circom related e2e are failing @azarpoor @ioedeveloper

hey, ill check this issue :+1:

2025-01-10 14:41 UTC, AmirH-A commented
hello hope you great 

how i can see the Tests ? for fixing this issue ?
@Aniket-Engg

2025-01-13 13:12 UTC, Aniket-Engg commented
> hello hope you great
> 
> how i can see the Tests ? for fixing this issue ? @Aniket-Engg

cc: @ioedeveloper

2025-03-26 15:12 UTC, Aniket-Engg commented
@ioedeveloper what should we do with it?

2025-03-27 14:27 UTC, AmirH-A commented
> @ioedeveloper what should we do with it?

hello , i can resolve the merge conflict, ill do it

2025-03-31 10:43 UTC, closed without merging