Chain Evm Map
ethereum/remix-project pull request #5313
Opened 2024-10-22 12:50 UTC by joeizang

2024-10-31 04:11 UTC, ryestew commented
I just tried switching in the Browser Wallet to Celo.  But the change in network in the wallet did not get reflected in Deploy & Run.

2024-11-04 15:28 UTC, ryestew requested changes

2024-11-04 15:29 UTC, ryestew commented
Strangely when I tried 1st to deploy to Celo Alfajores, I got this out of gas error:
![image](https://github.com/user-attachments/assets/e4a97762-1d8c-4fe3-993d-d801516156e9)

Then when I tried again I got the warning in this PR:
![image](https://github.com/user-attachments/assets/90f42221-53d5-4d1c-979c-c53bdb43600d)

2024-11-04 15:32 UTC, joeizang commented
> Strangely when I tried 1st to deploy to Celo Alfajores, I got this out of gas error: ![image](https://private-user-images.githubusercontent.com/6050001/382814096-e4a97762-1d8c-4fe3-993d-d801516156e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzQ1MDIsIm5iZiI6MTczMDczNDIwMiwicGF0aCI6Ii82MDUwMDAxLzM4MjgxNDA5Ni1lNGE5Nzc2Mi0xZDhjLTRmZTMtOTkzZC1kODAxNTE2MTU2ZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMTUzMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ4NWVmNDBiOGY2Y2QwZjBmZTMwY2ViNTA1ZTA3NTlkZDRmN2UyZjA4NTNhMThlNmE1YjkxZTQ0OWQ0MzlkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5Cbq5k_VIKF8zeLUYwEdZY7EiyBc9WrjVEF4GBSpqC4)
> 
> Then when I tried again I got the warning in this PR: ![image](https://private-user-images.githubusercontent.com/6050001/382814397-90f42221-53d5-4d1c-979c-c53bdb43600d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzQ1MDIsIm5iZiI6MTczMDczNDIwMiwicGF0aCI6Ii82MDUwMDAxLzM4MjgxNDM5Ny05MGY0MjIyMS01M2Q1LTRkMWMtOTc5Yy1jNTNiZGI0MzYwMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMTUzMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBmNjMwNWFjYjQ1NDU2MTEzNjU2MTBlMzU1Y2VhYWNkNWFjMTJkMjA2NDkyYzEwYmQ1Yjk3MGQ1MjEyZmEyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CxKbOCxgp_F1ZX0NuAJa4WGJJqvGp_YLh4fyubucx5M)

I am not sure  about the gas error though.

2024-11-04 15:34 UTC, joeizang commented on libs/remix-ui/run-tab/src/lib/actions/evmmap.ts
> +      { id: 44787, name: "Celo Alfajores Testnet" },
ok

2024-11-04 15:37 UTC, joeizang commented on libs/remix-ui/run-tab/src/lib/run-tab.tsx
> +              <p>The selected chain is not compatible with the selected EVM version. Please select a one of the options below.</p>
Done

2024-11-05 03:59 UTC, ryestew commented
I have one last question - if the EVM chain map gets outdated - can someone still deploy to the chain - they just hit the cancel button and then they deploy anyway - right?

2024-11-05 04:09 UTC, ryestew commented
There is something weird with the modals - I tried to deploy to Celo mainnet and I got 2 modals - the first disappeared to fast to see it and the second was the old modal:
![image](https://github.com/user-attachments/assets/6bfef923-8992-4197-8d41-851065dce145)

Something similar happens when I load this deployed instance - both entry modals appear and disappear.

2024-11-05 10:32 UTC, joeizang commented on libs/remix-ui/run-tab/src/lib/actions/evmmap.ts
> +      { id: 44787, name: "Celo Alfajores Testnet" },
done

2024-11-05 14:35 UTC, ryestew commented
The selected chain is not compatible with the EVM version that the Solidity contract had been compiled with. Please select a one of the options below.

If there is time, please change the above sentence to:
The smart contract has not been compiled with an EVM version that is compatible with the selected chain.

2024-11-05 14:42 UTC, joeizang commented
> The smart contract has not been compiled with an EVM version that is compatible with the selected chain.

Done. Please check

2024-11-05 14:50 UTC, ryestew approved these changes

2024-11-05 21:28 UTC, LianaHus commented
@joeizang we see a toaster about new settings which says "**udapp** is updating ..." Udapp is internal name and should be replaced by plugin _Display name_

2024-11-05 21:29 UTC, LianaHus commented
The rest looks LGTM

2024-11-06 07:08 UTC, merged