make height adjustment
ethereum/remix-project pull request #5401
Opened 2024-11-13 13:00 UTC by joeizang

2024-11-14 01:36 UTC, pr15il requested changes
I think `maxHeight` should be kept at `40rem` and `height` changed to `67%`

2024-11-14 02:33 UTC, pr15il requested changes

2024-11-14 02:33 UTC, pr15il commented on apps/remix-ide/src/app/components/popup-panel.tsx
> +          maxHeight: '60%',
```suggestion
          maxHeight: '40rem',
```

2024-11-14 02:33 UTC, pr15il commented on apps/remix-ide/src/app/components/popup-panel.tsx
> +          height: '60%',
```suggestion
          height: '67%',
```

2024-11-20 15:39 UTC, LianaHus commented on apps/remix-ide/src/app/components/popup-panel.tsx
> +          maxHeight: '60%',
I think we can even remove max-height

2024-11-20 16:38 UTC, joeizang commented on apps/remix-ide/src/app/components/popup-panel.tsx
> +          height: '60%',
Ok will have a look

2024-11-26 08:58 UTC, Aniket-Engg approved these changes
height is responsive now

2024-11-26 12:46 UTC, merged

2024-11-28 14:45 UTC, pr15il commented
When will it be released if I may know?