Fixed LearnEth can be launched with solidity unit testing plugin on the plugin manager
ethereum/remix-project pull request #5494
Opened 2024-12-14 13:40 UTC by skyler-coder

2024-12-19 22:21 UTC, ryestew reviewed
This works for me.

2024-12-19 22:25 UTC, ryestew commented
Thanks @skyler-coder!!!

2024-12-20 07:22 UTC, skyler-coder commented
you're welcome @ryestew

2024-12-20 07:44 UTC, bunsenstraat requested changes
this needs to be done in the learneth plugin, not here. it would make this impossible to find back later

2024-12-20 18:09 UTC, skyler-coder commented
I checked through the learnEth plugin to see how I could add solidityUnitTesting to it but to no avail, I think this method I used is best to resolve this issue @bunsenstraat

2024-12-21 14:35 UTC, skyler-coder commented
learnEth plugin does not have the permission to activate solidityUnitTesting plugin from a plugin call @bunsenstraat

2025-01-04 09:43 UTC, closed without merging