update Contributing.md
ethereum/remix-project pull request #5507
Opened 2024-12-18 02:59 UTC by ryestew

Please check if the explanation of adding a new language is correct.  I think there might be some problems.

2024-12-18 03:14 UTC, ryestew reviewed
Check line 57 about adding French.  I believe languages are added only in CrowdIn - but if you are making a new plugin you'll need to set up the new language's folder.  @LianaHus - could you confirm this?

2024-12-19 09:54 UTC, joeizang requested changes
I left a few comments regarding some sentences. But the javascript inside the index.js files isn't complete.

2024-12-19 09:54 UTC, joeizang commented on CONTRIBUTING.md
> +Everyone is welcome to contribute Remix's codebase. Please join our [Discord](https://discord.gg/mh9hFCKkEq) in case of any queries.
I think the sentence should read "Everyone is welcome to contribute to Remix's codebase"

2024-12-19 09:54 UTC, joeizang commented on CONTRIBUTING.md
> +Please conforms to the [standard](https://standardjs.com/) for code styles.
I feel this sentence should read a lot better than it does currently.

2024-12-19 09:54 UTC, joeizang commented on CONTRIBUTING.md
> +You can't be sure whether there is a match key in locale file or not. So its better to provide a `defaultMessage` prop.
This might read better this way: "You can't be sure whether there is a matched key in the locale file or not..."

2024-12-20 03:15 UTC, joeizang approved these changes
this seems fine for now. It can be improved in another pr

2024-12-21 07:00 UTC, merged