bumpup dev branch
ethereum/remix-project pull request #596
Opened 2020-11-18 11:21 UTC by LianaHus

2020-11-18 11:39 UTC, yann300 commented on package.json
> +  "version": "0.10.6-dev",
This should be `"version": "0.10.7-dev",`

2020-11-23 11:31 UTC, Aniket-Engg commented on package-lock.json
> +  "version": "0.10.6-dev",
This also needs to be updated

2020-11-23 11:40 UTC, cleytontiagosorinho approved these changes

2020-11-23 11:41 UTC, cleytontiagosorinho approved these changes

2020-11-23 11:41 UTC, cleytontiagosorinho approved these changes
bumpDev

2020-11-23 12:32 UTC, yann300 requested changes
`"version": "0.10.6-dev",` need to be updated in the lock file

2020-11-24 12:43 UTC, yann300 approved these changes

2020-11-24 12:44 UTC, merged