compiler configuration from URL e2e tests
ethereum/remix-project pull request #623
Opened 2020-11-25 09:32 UTC by Aniket-Engg

fixes #533

2020-11-25 12:15 UTC, cleytontiagosorinho reviewed
Muito bom

2020-11-25 12:18 UTC, cleytontiagosorinho requested changes
Sim por favor

2020-11-26 12:36 UTC, yann300 commented on apps/remix-ide-e2e/src/tests/url.test.ts
> +    .assert.containsText('#evmVersionSelector option[selected="selected"]', 'default')
the test suite should end with `.end()`

2020-11-27 09:37 UTC, yann300 approved these changes

2020-11-27 11:01 UTC, cleytontiagosorinho approved these changes
4843bd3e0987e68b27553422f001a6b406b77ec7

2020-11-27 11:55 UTC, merged