Create automation.md (PR automation)
ethereum/remix-project pull request #760
Opened 2021-01-20 15:17 UTC by yann300

2021-01-21 16:23 UTC, ryestew commented on automation.md
> + - **Out of the box github automerge** will merge PR once everything is green. It is activable from a pull request page.
A small edit:
**Out of the box, github automerge** will merge a PR once everything is green. It is activated from a pull request page.

2021-01-21 16:23 UTC, ryestew commented on automation.md
> +   It is activable by adding the `autosquash` label.
It is activated

2021-01-22 14:45 UTC, ryestew requested changes
Please change the word  **activable** to **activated** - see the specifics in my 2 comments

2021-01-22 15:01 UTC, yann300 commented
@ryestew yes that what I did .did I miss something ?

2021-01-22 15:56 UTC, ryestew approved these changes

2021-01-22 15:56 UTC, merged